Apps/Adopcion/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from Apps.Adopcion.views import SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

app_name = 'adopcion'
urlpatterns = [
    # pat(r'index$', index_adopcion),
     path('listar', SolicitudList.as_view(), name='solicitud_listar'),
     path('nueva', SolicitudCreate.as_view(), name='solicitud_crear'),
     path('editar/<int:pk>', SolicitudUpdate.as_view(), name='solicitud_editar'),
     path('eliminar/<int:pk>', SolicitudDelete.as_view(), name='solicitud_eliminar'),

]

Apps/Mascota/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from Apps.Mascota.views import Index, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete,\
 VacunaList, VacunaCreate, VacunaUpdate, VacunaDelete

app_name = 'mascota'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('nuevo', MascotaCreate.as_view(), name='mascota_crear'),
    path('listar', MascotaList.as_view(), name='mascota_listar'),
    path('editar/<int:pk>', MascotaUpdate.as_view(), name='mascota_editar'),
    path('eliminar/<int:pk>', MascotaDelete.as_view(), name='mascota_eliminar'),

    path('Vnuevo', VacunaCreate.as_view(), name='vacuna_crear'),
    path('Vlistar', VacunaList.as_view(), name='vacuna_listar'),
    path('Veditar/<int:pk>', VacunaUpdate.as_view(), name='vacuna_editar'),
    path('Veliminar/<int:pk>', VacunaDelete.as_view(), name='vacuna_eliminar'),
]

Refugio/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog



urlpatterns = [
    path('', include('Apps.Mascota.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('usuario/', include('Apps.Usuario.urls')),
    path('mascota/', include('Apps.Mascota.urls', namespace='mascota',)),
    path('adopcion/', include('Apps.Adopcion.urls', namespace='adopcion')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

Apps/Adopcion/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.
class Persona(models.Model):
    """docstring for Persona."""
    Nombre = models.CharField(max_length = 50)
    Apellido = models.CharField(max_length = 50)
    Edad = models.IntegerField()
    Telefono = models.CharField(max_length=12, null=True)
    Email = models.EmailField()
    Domicilio = models.TextField()


    def __str__(self):
        return "%s %s" % (self.Nombre, self.Apellido )

class Solicitud(models.Model):
    """docstring for Solicitud."""
    Persona = models.ForeignKey(Persona , verbose_name='Persona', null=True, blank=True,  on_delete=models.CASCADE )
    Numero_mascotas = models.IntegerField()
    Razones = models.TextField()

    def __str__(self):
        return "%s" % (self.id )

Apps/Adopcion/forms.py
from django import forms
from Apps.Adopcion.models import Persona, Solicitud
from betterforms.multiform import MultiModelForm
# instalamos pip install django-betterforms

class PersonaForm(forms.ModelForm):

	class Meta:
		model = Persona
		fields = [
			'Nombre',
			'Apellido',
			'Edad',
			'Telefono',
			'Email',
			'Domicilio',
		]
		labels = {
			'Nombre': 'Nombre',
			'Apellido': 'Apellidos',
			'Edad': 'Edad',
			'Telefono': 'Teléfono',
			'Email': 'Correo electrónico',
			'Domicilio': 'Domicilio',
		}
		widgets = {
			'Nombre':forms.TextInput(attrs={'class':'form-control'}),
			'Apellido':forms.TextInput(attrs={'class':'form-control'}),
			'Edad':forms.TextInput(attrs={'class':'form-control'}),
			'Telefono':forms.TextInput(attrs={'class':'form-control'}),
			'Email':forms.TextInput(attrs={'class':'form-control'}),
			'Domicilio':forms.Textarea(attrs={'class':'form-control'}),
		}


class SolicitudForm(forms.ModelForm):

	class Meta:
		model = Solicitud
		fields = [
			'Numero_mascotas',
			'Razones',
		]
		labels = {
			'Numero_mascotas': 'Numero de mascotas',
			'Razones': 'Razones para adoptar',

		}
		widgets = {
			'Numero_mascotas':forms.TextInput(attrs={'class':'form-control'}),
			'Razones':forms.Textarea(attrs={'class':'form-control'}),
		}

Apps/Adopcion/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.shortcuts import render, redirect
from Apps.Adopcion.forms import SolicitudForm, PersonaForm
from Apps.Adopcion.models import Persona, Solicitud
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class SolicitudList(LoginRequiredMixin, ListView):
	model = Solicitud
	template_name = 'adopcion/solicitud_list.html'
	paginate_by = 5

class SolicitudCreate(LoginRequiredMixin, CreateView):
	model = Solicitud
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')

	def get_context_data(self, **kwargs):
		context = super(SolicitudCreate, self).get_context_data(**kwargs)
		if 'form' not in context:
			context['form'] = self.form_class(self.request.GET)
		if 'form2' not in context:
			context['form2'] = self.second_form_class(self.request.GET)
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		form2 = self.second_form_class(request.POST)
		if form.is_valid() and form2.is_valid():
			solicitud = form.save(commit=False)
			solicitud.Persona = form2.save()
			solicitud.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return self.render_to_response(self.get_context_data(form=form, form2=form2))


class SolicitudUpdate(LoginRequiredMixin, UpdateView):
	model = Solicitud
	second_model = Persona
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')

	def get_context_data(self, **kwargs):
		    context = super(SolicitudUpdate, self).get_context_data(**kwargs)
		    pk = self.kwargs.get('pk', 0)
		    solicitud = self.model.objects.get(id=pk)
		    persona = self.second_model.objects.get(id=solicitud.Persona_id)
		    if 'form' not in context:
		    	context['form'] = self.form_class()
		    if 'form2' not in context:
		    	context['form2'] = self.second_form_class(instance=persona)
		    context['id'] = pk
		    return context

	def post(self, request, *args, **kwargs):
			self.object = self.get_object
			id_solicitud = kwargs['pk']
			Solicitud = self.model.objects.get(id=id_solicitud)
			Persona = self.second_model.objects.get(id=Solicitud.Persona_id)
			form = self.form_class(request.POST, instance=Solicitud)
			form2 = self.second_form_class(request.POST, instance=Persona)
			if form.is_valid() and form2.is_valid():
				form.save()
				form2.save()
				return HttpResponseRedirect(self.get_success_url())
			else:
				return HttpResponseRedirect(self.get_success_url())


class SolicitudDelete(LoginRequiredMixin, DeleteView):
	model = Solicitud
	template_name = 'adopcion/solicitud_delete.html'
	success_url = reverse_lazy('adopcion:solicitud_listar')

templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	<center>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% csrf_token %}
			<h3>¿Desea eliminar la solicitud de {{ object.Persona }}?</h3>
			<center>
				<button class="btn btn-danger" type="submit">Sí, eliminar</button>
				<a class= "btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
			</center>
		</div>
	</div>
	</center>
</form>
{% endblock %}

templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<div class="col-md-8 col-md-offset-2">
		{{ form2.as_p }}
		{{ form.as_p }}
			<div class="form-group">
				<button class="btn btn-primary" type="submit">Guardar</button>
			</div>
		</div>
</form>
{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		{% if object_list %}
		<tr>
			<td align='center'>No. Solicitud</td>
			<td align='center'>Adoptante</td>
			<td align='center'>No. Mascotas</td>
			<td align='center'>Razones</td>
			<td align='center'>Acciones</td>
		</tr>
		{% endif %}
	</thead>
	<tbody>
		{% if object_list %}
		{% for solicitud in object_list %}
		<tr>
			<td align='center'>{{ solicitud.id }}</td>
			<td align='center'>{{ solicitud.Persona }}</td>
			<td align='center'>{{ solicitud.Numero_mascotas }}</td>
			<td align='center'>{{ solicitud.Razones }}</td>

			<td align='center'>
				<a class="btn btn-primary" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
				<a style="margin-left: 20px" class="btn btn-danger" href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de solicitudes</h1>
		{% endif %}
	</tbody>
</table>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">

			<ul class="pager">
				<li>
					{% if page_obj.has_previous %}
			       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
					{% endif %}
			        </li>
				<li>
					{% if page_obj.has_next %}
			     	 <a style="margin-left: 300px" href="?page={{ page_obj.next_page_number }}">Next</a>
			    	{% endif %}
			    </li>
			</ul>

		</div>
	</div>
</div>
{% endblock%}