Apps/Adopcion/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from Apps.Adopcion.views import SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

app_name = 'adopcion'
urlpatterns = [
    # pat(r'index$', index_adopcion),
     path('listar', SolicitudList.as_view(), name='solicitud_listar'),
     path('nueva', SolicitudCreate.as_view(), name='solicitud_crear'),
     path('editar/<int:pk>', SolicitudUpdate.as_view(), name='solicitud_editar'),
     path('eliminar/<int:pk>', SolicitudDelete.as_view(), name='solicitud_eliminar'),

]

Apps/Mascota/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from Apps.Mascota.views import Index, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete,\
 VacunaList, VacunaCreate, VacunaUpdate, VacunaDelete

app_name = 'mascota'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('nuevo', MascotaCreate.as_view(), name='mascota_crear'),
    path('listar', MascotaList.as_view(), name='mascota_listar'),
    path('editar/<int:pk>', MascotaUpdate.as_view(), name='mascota_editar'),
    path('eliminar/<int:pk>', MascotaDelete.as_view(), name='mascota_eliminar'),

    path('Vnuevo', VacunaCreate.as_view(), name='vacuna_crear'),
    path('Vlistar', VacunaList.as_view(), name='vacuna_listar'),
    path('Veditar/<int:pk>', VacunaUpdate.as_view(), name='vacuna_editar'),
    path('Veliminar/<int:pk>', VacunaDelete.as_view(), name='vacuna_eliminar'),
]

Refugio/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog



urlpatterns = [
    path('', include('Apps.Mascota.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('usuario/', include('Apps.Usuario.urls')),
    path('mascota/', include('Apps.Mascota.urls', namespace='mascota',)),
    path('adopcion/', include('Apps.Adopcion.urls', namespace='adopcion')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Refugio{% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="{% url 'index:index' %}">INICIO</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'mascota:mascota_crear' %}">Registrar Mascota</a></li>
				                        	<li><a href="{% url 'mascota:mascota_listar' %}">Listar Mascotas</a></li>
				                        </ul>
		                      		</li>
			                        <li class="dropdown">
			                        	<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a></li>
				                          	<li><a href="{% url 'adopcion:solicitud_listar' %}">Listar solicitudes</a></li>
			                        	</ul>
			                        </li>
															<li class="dropdown">
															 <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Vacunas<span class="caret"></span></a>
															 <ul class="dropdown-menu" role="menu">
																	 <li><a href="{% url 'mascota:vacuna_crear' %}">Agregar</a></li>
																	 <li><a href="{% url 'mascota:vacuna_listar' %}">Listar Vacunas</a></li>
															 </ul>
														 </li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="{% url 'logout' %}">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
<script type="text/javascript" src="{% static '/admin/js/core.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static '/admin/css/widgets.css' %}">

{{ form.media }}        {# Form required JS and CSS #}
	{% block extrajs %}
	{% endblock %}


</body>
</html>

templates/base/bootstrap_defaults.html
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

templates/base/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- DataTables -->
<!-- <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"> -->
<!-- <link href="https://cdn.datatables.net/fixedcolumns/3.2.6/css/fixedColumns.dataTables.min.css"> -->
<!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css"> -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
<!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/> -->

templates/base/js.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>


<!-- DataTables js -->
<!-- <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"> </script> -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js"></script> -->
<script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>


<!-- jQuery Modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>