Apps/Mascota/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from Apps.Mascota.views import Index, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete,\
 VacunaList, VacunaCreate, VacunaUpdate, VacunaDelete

app_name = 'mascota'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('nuevo', MascotaCreate.as_view(), name='mascota_crear'),
    path('listar', MascotaList.as_view(), name='mascota_listar'),
    path('editar/<int:pk>', MascotaUpdate.as_view(), name='mascota_editar'),
    path('eliminar/<int:pk>', MascotaDelete.as_view(), name='mascota_eliminar'),

    path('Vnuevo', VacunaCreate.as_view(), name='vacuna_crear'),
    path('Vlistar', VacunaList.as_view(), name='vacuna_listar'),
    path('Veditar/<int:pk>', VacunaUpdate.as_view(), name='vacuna_editar'),
    path('Veliminar/<int:pk>', VacunaDelete.as_view(), name='vacuna_eliminar'),
]

Refugio/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog



urlpatterns = [
    path('', include('Apps.Mascota.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('usuario/', include('Apps.Usuario.urls')),
    path('mascota/', include('Apps.Mascota.urls', namespace='mascota',)),
    path('adopcion/', include('Apps.Adopcion.urls', namespace='adopcion')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

templates/vacuna/vacuna_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	<center>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% csrf_token %}
			<h3>¿Desea eliminar el registro de {{ object.Nombre }}?</h3>
			<center>
				<button class="btn btn-danger" type="submit">Sí, eliminar</button>
				<a class= "btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
			</center>
		</div>
	</div>
	</center>
</form>
{% endblock %}

/Refugio-vistas-clases/.git/

templates/vacuna/vacuna_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% csrf_token %}
			{{ form.as_p }}


					<div class="form-group">
						<button class="btn btn-primary" type="submit">Agregar</button>
					</div>

		</div>
	</div>

</form>
{% endblock %}

templates/vacuna/vacuna_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		{% if object_list %}
		<tr>
			<td align='center'>#</td>
			<td align='center'>Nombre</td>
			<td align='center'>Acciones</td>
		</tr>
		{% endif %}

	</thead>
	<tbody>
		{% if object_list %}
		{% for vacuna in object_list %}
		<tr>
			<td align='center'>{{ vacuna.id }}</td>
			<td align='center'>{{ vacuna.Nombre }}</td>
			<td align='center'>
				<a class="btn btn-primary" href="{% url 'mascota:vacuna_editar' vacuna.id %}">Editar</a>
				<a style="margin-left: 20px" class="btn btn-danger" href="{% url 'mascota:vacuna_eliminar' vacuna.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de vacunas</h1>
		{% endif %}
	</tbody>
</table>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">

			<ul class="pager">
				<li>
					{% if page_obj.has_previous %}
			       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
					{% endif %}
			        </li>
				<li>
					{% if page_obj.has_next %}
			     	 <a style="margin-left: 300px" href="?page={{ page_obj.next_page_number }}">Next</a>
			    	{% endif %}
			    </li>
			</ul>

		</div>
	</div>
</div>
{% endblock%}