Apps/Mascota/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from Apps.Mascota.views import Index, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete,\
 VacunaList, VacunaCreate, VacunaUpdate, VacunaDelete

app_name = 'mascota'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('nuevo', MascotaCreate.as_view(), name='mascota_crear'),
    path('listar', MascotaList.as_view(), name='mascota_listar'),
    path('editar/<int:pk>', MascotaUpdate.as_view(), name='mascota_editar'),
    path('eliminar/<int:pk>', MascotaDelete.as_view(), name='mascota_eliminar'),

    path('Vnuevo', VacunaCreate.as_view(), name='vacuna_crear'),
    path('Vlistar', VacunaList.as_view(), name='vacuna_listar'),
    path('Veditar/<int:pk>', VacunaUpdate.as_view(), name='vacuna_editar'),
    path('Veliminar/<int:pk>', VacunaDelete.as_view(), name='vacuna_eliminar'),
]

Refugio/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog



urlpatterns = [
    path('', include('Apps.Mascota.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('usuario/', include('Apps.Usuario.urls')),
    path('mascota/', include('Apps.Mascota.urls', namespace='mascota',)),
    path('adopcion/', include('Apps.Adopcion.urls', namespace='adopcion')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

Apps/Mascota/models.py
from django.db import models
from django.contrib.auth import get_user_model
from Apps.Adopcion.models import Persona

OPCIONES_GENERO = (
    ('M' , 'Macho'),
    ('H' , 'Hembra'),
)

# Create your models here.
class Vacuna(models.Model):
    """docstring for Vacuna."""
    Nombre = models.CharField(max_length = 50)

    def __str__(self):
        return "%s" % (self.Nombre )



class Mascota(models.Model):
    """docstring for Mascota."""
    Nombre = models.CharField(max_length = 50)
    Sexo = models.CharField(max_length=1, choices = OPCIONES_GENERO,)
    Edad_aproximada = models.IntegerField()
    Fecha_rescate = models.DateField()
    Persona = models.ForeignKey(Persona,  verbose_name='Persona', null=True, blank=True, on_delete=models.CASCADE )
    Vacuna = models.ManyToManyField(Vacuna, verbose_name='Vacuna', blank=True)

    def __str__(self):
        return "%s" % (self.Nombre )

Apps/Mascota/forms.py
from django import forms
from Apps.Mascota.models import Mascota, Vacuna
from django.contrib.admin import widgets

class MascotaForm(forms.ModelForm):

     class Meta:
         model = Mascota

         fields = [
         'Nombre',
         'Sexo',
         'Edad_aproximada',
         'Fecha_rescate',
         'Persona',
         'Vacuna',
         ]

         labels = {
         'Nombre':'Nombre',
         'Sexo':'Sexo',
         'Edad_aproximada':'Edad aproximada',
         'Fecha_rescate':'Fecha del rescate',
         'Persona':'Adoptante',
         'Vacuna':'Vacuna',
         }

         widgets = {
         'Nombre': forms.TextInput(attrs={'class':'form-control'}),
         'Sexo': forms.Select(attrs={'class':'form-control'}),
         'Edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
         'Fecha_rescate': widgets.AdminDateWidget(),
         'Persona': forms.Select(attrs={'size': '1','class':'form-control'}),
         'Vacuna': forms.CheckboxSelectMultiple(),
         }


class VacunaForm(forms.ModelForm):

		class Meta:
				model = Vacuna
				fields = [
					'Nombre'
				]
				labels = {
					'Nombre': 'Nombre de vacuna',

				}
				widgets = {
					'Nombre':forms.TextInput(attrs={'class':'form-control'}),
				}

Apps/Mascota/views.py
from django import forms
from django.shortcuts import render, redirect
from Apps.Mascota.forms import MascotaForm, VacunaForm
from Apps.Mascota.models import Mascota, Vacuna
from django.views.generic import TemplateView , ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class Index( ListView):
	model = Mascota
	template_name = 'mascota/index.html'

class MascotaList(LoginRequiredMixin, ListView):
	model = Mascota
	template_name = 'mascota/mascota_list.html'
	paginate_by = 5

class MascotaCreate(LoginRequiredMixin, CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')


class MascotaUpdate(LoginRequiredMixin, UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')


class MascotaDelete(LoginRequiredMixin, DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')

class VacunaList(LoginRequiredMixin, ListView):
		model = Vacuna
		template_name = 'vacuna/vacuna_list.html'
		paginate_by = 5

class VacunaCreate(LoginRequiredMixin, CreateView):
		model = Vacuna
		form_class = VacunaForm
		template_name = 'vacuna/vacuna_form.html'
		success_url = reverse_lazy('mascota:vacuna_listar')


class VacunaUpdate(LoginRequiredMixin, UpdateView):
		model = Vacuna
		form_class = VacunaForm
		template_name = 'vacuna/vacuna_form.html'
		success_url = reverse_lazy('mascota:vacuna_listar')



class VacunaDelete(LoginRequiredMixin, DeleteView):
		model = Vacuna
		template_name = 'vacuna/vacuna_delete.html'
		success_url = reverse_lazy('mascota:vacuna_listar')

templates/mascota/index.html
{% extends 'base/base.html' %}
{% block navbar %}
  <div class="bs-docs-section clearfix">
      <div class="row">
          <div class="col-lg-12">
              <div class="bs-component">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                          <a class="navbar-brand" href="{% url 'index:index' %}">INICIO</a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                  <li><a href="{% url 'mascota:mascota_listar' %}">Entrar</a></li>
                              </ul>
                            </li>
                        </ul>
                  </div>
              </nav>
          </div>
          </div>
      </div>
  </div>
{% endblock %}
{% block content %}
<h1>Refugio Corazon</h1>
<a>Solos una agrupacion dedicada al rescate de animales, para poder otorgarles un hogar seguro.</a>
<img src="static/image/territorio-de-zaguates.jpg" alt=""></img>
{% endblock%}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	<center>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% csrf_token %}
			<h3>¿Desea eliminar el registro de {{ object.Nombre }}?</h3>
			<center>
			<button class="btn btn-danger" type="submit">Sí, eliminar</button>
			<a class= "btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
			</center>
		</div>
	</div>
	</center>
</form>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			{% csrf_token %}
			{{ form.as_p }}
<style>.calendar>table>caption{caption-side:unset}</style><!--caption fix for bootstrap4-->
			<div class="form-group">
<a class="btn btn-primary" href="{% url 'mascota:vacuna_crear' %}">Agregar Vacuna</a>
			</div>
				<div class="form-group">
				<button class="btn btn-primary" type="submit">Agregar Mascota</button>
		</div>
	</div>
</div>
</form>
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		{% if object_list %}
		<tr>
			<td align='center'>Numero</td>
			<td align='center'>Nombre</td>
			<td align='center'>Sexo</td>
			<td align='center'>Edad</td>
			<td align='center'>Fecha de Rescate</td>
			<td align='center'>Vacunas</td>
			<td align='center'>Adoptante</td>
			<td align='center'>Acciones</td>
		</tr>
		{% endif %}

	</thead>
	<tbody>
		{% if object_list %}
		{% for mascota in object_list %}
		<tr>
			<td align='center'>{{ mascota.id }}</td>
			<td align='center'>{{ mascota.Nombre }}</td>
			<td align='center'>{{ mascota.Sexo }}</td>
			<td align='center'>{{ mascota.Edad_aproximada }}</td>
			<td align='center'>{{ mascota.Fecha_rescate }}</td>
			<td>
			<ul>{% for vacuna in mascota.Vacuna.all %}
				<li align='center'>
					{{vacuna.Nombre}}
				</li>
				{% endfor %}
			</ul>
    		</td>
			<td align='center'> {{ mascota.Persona }}</td>
			<td align='center'>
				<a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
				<a style="margin-left: 20px" class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de mascotas</h1>
		{% endif %}
	</tbody>
</table>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">

			<ul class="pager">
				<li>
					{% if page_obj.has_previous %}
			       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
					{% endif %}
			        </li>
				<li>
					{% if page_obj.has_next %}
			     	 <a style="margin-left: 300px" href="?page={{ page_obj.next_page_number }}">Next</a>
			    	{% endif %}
			    </li>
			</ul>

		</div>
	</div>
</div>
{% endblock%}